env:
  buildozer_version: git+https://github.com/antocuni/buildozer.git@antocuni/aab-support-and-fileprovider
name: CI
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # used to cache dependencies with a timeout
      - name: Get Date
        id: get-date
        run: |
          echo "::set-output name=date::$(/bin/date -u "+%Y%m%d")"
        shell: bash

      - name: Cache Buildozer global directory
        uses: actions/cache@v2
        with:
          path: .buildozer_global
          key: buildozer-global-${{ hashFiles('buildozer.spec') }} # Replace with your path

      - uses: actions/cache@v2
        with:
          path: .buildozer
          key: ${{ runner.os }}-${{ steps.get-date.outputs.date }}-${{ hashFiles('buildozer.spec') }}

      - name: TryUpdate1
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          command: (echo y ; echo y; echo y; echo y; echo y; echo y ;) | buildozer -v android update 
          allow_failure: true
          buildozer_version: master
          
      - name: TryUpdate2
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer11
        with:
          command: (echo y ; echo y; echo y; echo y; echo y; echo y ;) | buildozer -v android update 
          allow_failure: true
          buildozer_version: master
          
      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer2
        if: always()
        with:
          command:  buildozer -v android release 
          buildozer_version: master

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: package
          path: ${{ steps.buildozer.outputs.filename }}
